[default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
remappings = []
libraries = []
cache = true
cache_path = 'cache'
force = false
evm_version = 'london'
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 200
verbosity = 2
ignored_error_codes = []
fuzz_runs = 5000
fuzz_max_local_rejects = 65536
fuzz_max_global_rejects = 1024
ffi = false
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 1
chain_id = 31337
gas_limit = 9223372036854775807
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1
block_difficulty = 0
gas_reports = ["*"]
no_storage_caching = false
rpc_storage_caching = { chains = "all", endpoints = "remote" }
extra_output = []
extra_output_files = []
bytecode_hash = "ipfs"
sparse_mode = false
via_ir = false
revert_strings = "default"
#optimizer_details = None
#eth_rpc_url = None
#etherscan_api_key = None
#test_pattern= None
#test_pattern_inverse = None
#contract_pattern = None
#contract_pattern_inverse = None
#path_pattern = None
#path_pattern_inverse = None
#block_gas_limit = None
memory_limit = 33554432
names = true
sizes = true

[verbose]
verbosity = 4
